export const SET_CREATE_ROOM_DIALOG_VISIBILITY =
  "SET_CREATE_ROOM_DIALOG_VISIBILITY";
export const SET_CHANGE_NAME_DIALOG_VISIBILITY =
  "SET_CHANGE_NAME_DIALOG_VISIBILITY";
export const SET_USER_NAME = "SET_USER_NAME";
export const ADD_ROOM = "ADD_ROOM";
export const SET_SELECTED_ROOM = "SET_SELECTED_ROOM";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const SET_MESSAGES = "SET_MESSAGES";
export const FETCH_ROOMS = "FETCH_ROOMS";
export const SET_ROOMS = "SET_ROOMS";
export const ADD_EVENT_LISTENER_ROOMS = "ADD_EVENT_LISTENER_ROOMS";
export const ADD_EVENT_LISTENER_MESSAGES = "ADD_EVENT_LISTENER_MESSAGES";
