export const SET_CREATE_ROOM_DIALOG_VISIBILITY =
  "SET_CREATE_ROOM_DIALOG_VISIBILITY";
export const SET_CHANGE_NAME_DIALOG_VISIBILITY =
  "SET_CHANGE_NAME_DIALOG_VISIBILITY";
export const SET_USER_NAME = "SET_USER_NAME";
export const ADD_ROOM = "ADD_ROOM";
export const SET_SELECTED_ROOM = "SET_SELECTED_ROOM";
export const ADD_MESSAGE = "ADD_MESSAGE";
